---
title: "Draft TFM"
author: "Victoria Costas"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
---

```{r global_options, include=T, echo = F}
knitr::opts_chunk$set(echo = T, warning=FALSE, message=FALSE)
```

```{=html}
<style>
body {
text-align: justify}
</style>
```

-------------------------------------------COMMENTS AND EXPLANATIONS ARE MISSING------------------------------------------------------


## Libraries

```{r}
library(tidyverse)
library(dplyr)
library(mice)
library(zoo)
library(randomForest)
library(missForest)
library(ggplot2)
library(patchwork)
library(factoextra)
```

## Read the data

```{r}
data <- read_csv("./data/merged_data.csv")

#remove the first row for clarity
data <- data[, -1]
```

### Descriptive analysis

Some preliminary analysis:

```{r}
summary(data)
```

### Some pre-processing

```{r}
# Remove columns from 2000 to 2009 and column 2022
columns_to_remove <- c(2000:2009, 2022)
data <- data[, !names(data) %in% columns_to_remove]

#order the columns
data <- data[, rev(order(colnames(data)))]

#Check NAs
na_percentage_by_country <- data.frame(geo_time = data$geo_time,
                                       na_percentage = apply(data[, -(1:2)], 1, function(x) sum(is.na(x)) / length(x) * 100))

na_percentage_by_year <- data.frame(year = colnames(data)[-(1:2)],
                                    na_percentage = apply(data[, -(1:2)], 2, function(x) sum(is.na(x)) / length(x) * 100))

```


```{r}
# Reshape the dataset to long format
data_long <- data %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value")

# Remove duplicates and compute the mean by indicator, country, and year
data_mean <- data_long %>%
  group_by(indicator, geo_time, year) %>%
  summarize(mean_value = mean(value, na.rm = TRUE))

# Pivot the dataset to wide format with indicator values as column names
data_wide <- data_mean %>%
  pivot_wider(names_from = indicator, values_from = mean_value)

```


### Imputation

```{r}
# Remove the 'X' prefix from the 'year' column
data_wide$year <- sub("^X", "", data_wide$year)
#Change NaN to NA
data_wide <- lapply(data_wide, function(x) {x[is.nan(x)] <- NA; x})
data_wide <- do.call(data.frame, data_wide)

#Linear regression
mice_object <- mice(data_wide[, -(1:2)], method = "norm", m = 10)
imputed_data <- complete(mice_object)
data_lm <- cbind(data_wide[, 1:2], imputed_data) #there are still some NAs --> Inherent missingness pattern

#Random Forest
mice_object <- mice(data_wide[, -(1:2)], method = "rf")
imputed_data <- complete(mice_object)
data_rf <- cbind(data_wide[, 1:2], imputed_data)

#Miss Forest
imputed_data <- missForest(data_wide[, -(1:2)])
data_mf <- cbind(data_wide[, 1:2], imputed_data$ximp)

```

```{r}
###Justify why i use miss forest.............................
```

## Clustering analysis

```{r}
X <- data_mf %>% select(-c(year, geo_time))
```

```{r}
set.seed(123)
k = 5
fit <- kmeans(scale(X), centers = k, nstart = 10000)
groups <- fit$cluster
barplot(table(groups), col = "#FF00FF")
cluster_labels <- fit$cluster


fviz_nbclust(X, kmeans, method = 'wss', k.max = 10, nstart = 1000) 
```

```{r}
set.seed(123)
k = 4
fit <- kmeans(scale(X), centers = k, nstart = 10000)
groups <- fit$cluster
barplot(table(groups), col = "#FF00FF")
cluster_labels <- fit$cluster
```


```{r}
centers=fit$centers

barplot(centers[1,], las=2, col="#FF00FF")
barplot(centers[2,], las=2, col="#FF00FF")
barplot(centers[3,], las=2, col="#FF00FF")
barplot(centers[4,], las=2, col="#FF00FF")

```

## Clusplot 

```{r}
names <- data_mf$geo_time

#clusplot
fviz_cluster(fit, data = X, geom = c("point"),ellipse.type = 'norm', pointsize=1)+
  theme_minimal()+geom_text(label=names,hjust=0, vjust=0,size=2,check_overlap = T)+scale_fill_brewer(palette="Paired")
```

```{r}
fit.km <-eclust(X, "kmeans", stand = T, k = 4, graph = T)
```






















